In [1]:
import pandas as pd

In [2]:
rides = pd.read_csv("/Users/kcarnold/Downloads/2011-capitalbikeshare-tripdata.zip")
rides.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1226767 entries, 0 to 1226766
Data columns (total 9 columns):
Duration                1226767 non-null int64
Start date              1226767 non-null object
End date                1226767 non-null object
Start station number    1226767 non-null int64
Start station           1226767 non-null object
End station number      1226767 non-null int64
End station             1226767 non-null object
Bike number             1226767 non-null object
Member type             1226767 non-null object
dtypes: int64(3), object(6)
memory usage: 84.2+ MB

In [7]:
rides.head()

,Duration,Start date,End date,Start station number,Start station,End station number,End station,Bike number,Member type,start
0,3548,2011-01-01 00:01:29,2011-01-01 01:00:37,31620,5th & F St NW,31620,5th & F St NW,W00247,Member,2011-01-01 00:01:29
1,346,2011-01-01 00:02:46,2011-01-01 00:08:32,31105,14th & Harvard St NW,31101,14th & V St NW,W00675,Casual,2011-01-01 00:02:46
2,562,2011-01-01 00:06:13,2011-01-01 00:15:36,31400,Georgia & New Hampshire Ave NW,31104,Adams Mill & Columbia Rd NW,W00357,Member,2011-01-01 00:06:13
3,434,2011-01-01 00:09:21,2011-01-01 00:16:36,31111,10th & U St NW,31503,Florida Ave & R St NW,W00970,Member,2011-01-01 00:09:21
4,233,2011-01-01 00:28:26,2011-01-01 00:32:19,31104,Adams Mill & Columbia Rd NW,31106,Calvert & Biltmore St NW,W00346,Casual,2011-01-01 00:28:26

In [8]:
del rides["Start station"]
del rides["End station"]

In [4]:
rides['Member type'].value_counts()

Member     979814
Casual     246949
Unknown         4
Name: Member type, dtype: int64

In [5]:
rides = rides[rides['Member type'] != "Unknown"]

In [6]:
rides['Member type'].value_counts()

Member    979814
Casual    246949
Name: Member type, dtype: int64

In [9]:
rides['start'] = pd.to_datetime(rides['Start date'])
rides['start'].iloc[0]

Timestamp('2011-01-01 00:01:29')

In [14]:
rides['start'].tail(10).dt.strftime("%Y-%m-%d")

1226757    2011-12-31
1226758    2011-12-31
1226759    2011-12-31
1226760    2011-12-31
1226761    2011-12-31
1226762    2011-12-31
1226763    2011-12-31
1226764    2011-12-31
1226765    2011-12-31
1226766    2011-12-31
Name: start, dtype: object

In [55]:
rides['date'] = rides['start'].dt.date#strftime("%Y-%m-%d")
rides['hour'] = rides['start'].dt.hour

In [56]:
grouped_as_index = rides.groupby(['date', 'hour', 'Member type']).size()
rides_by_hour = grouped_as_index.to_frame("rides").reset_index()
rides_by_hour

             date  hour Member type  rides
0      2011-01-01     0      Casual      3
1      2011-01-01     0      Member     13
2      2011-01-01     1      Casual      8
3      2011-01-01     1      Member     30
4      2011-01-01     2      Casual      5
5      2011-01-01     2      Member     26
6      2011-01-01     3      Casual      3
7      2011-01-01     3      Member      9
8      2011-01-01     4      Member      1
9      2011-01-01     5      Member      1
10     2011-01-01     6      Casual      2
11     2011-01-01     7      Casual      1
12     2011-01-01     7      Member      2
13     2011-01-01     8      Casual      1
14     2011-01-01     8      Member      7
15     2011-01-01     9      Casual      8
16     2011-01-01     9      Member      6
17     2011-01-01    10      Casual     12
18     2011-01-01    10      Member     22
19     2011-01-01    11      Casual     26
20     2011-01-01    11      Member     30
21     2011-01-01    12      Casual     29
22     2011-01-01    12      Member     54
23     2011-01-01    13      Casual     47
24     2011-01-01    13      Member     47
25     2011-01-01    14      Casual     34
26     2011-01-01    14      Member     69
27     2011-01-01    15      Casual     40
28     2011-01-01    15      Member     67
29     2011-01-01    16      Casual     41
...           ...   ...         ...    ...
16387  2011-12-31     9      Casual     18
16388  2011-12-31     9      Member     71
16389  2011-12-31    10      Casual     20
16390  2011-12-31    10      Member    108
16391  2011-12-31    11      Casual     65
16392  2011-12-31    11      Member    152
16393  2011-12-31    12      Casual     93
16394  2011-12-31    12      Member    178
16395  2011-12-31    13      Casual    108
16396  2011-12-31    13      Member    200
16397  2011-12-31    14      Casual    115
16398  2011-12-31    14      Member    181
16399  2011-12-31    15      Casual     89
16400  2011-12-31    15      Member    161
16401  2011-12-31    16      Casual     52
16402  2011-12-31    16      Member    139
16403  2011-12-31    17      Casual     28
16404  2011-12-31    17      Member     99
16405  2011-12-31    18      Casual     13
16406  2011-12-31    18      Member     80
16407  2011-12-31    19      Casual     19
16408  2011-12-31    19      Member     70
16409  2011-12-31    20      Casual      8
16410  2011-12-31    20      Member     63
16411  2011-12-31    21      Casual      2
16412  2011-12-31    21      Member     50
16413  2011-12-31    22      Casual      2
16414  2011-12-31    22      Member     34
16415  2011-12-31    23      Casual      4
16416  2011-12-31    23      Member     26

[16417 rows x 4 columns]

In [57]:
from pandas.tseries.holiday import USFederalHolidayCalendar

In [58]:
import datetime

In [59]:
holidays = pd.DataFrame({
    'date': USFederalHolidayCalendar().holidays(datetime.date(2011,1,1), datetime.date(2015,12,31)).date,
    'is_holiday': True})
holidays.head()

         date  is_holiday
0  2011-01-17        True
1  2011-02-21        True
2  2011-05-30        True
3  2011-07-04        True
4  2011-09-05        True

In [63]:
# too few
rides_by_hour_with_holidays = pd.merge(
    rides_by_hour,
    holidays,
    left_on='date',
    right_on='date')
rides_by_hour_with_holidays.head()

         date  hour Member type  rides  is_holiday
0  2011-01-17     0      Casual      1        True
1  2011-01-17     0      Member     16        True
2  2011-01-17     1      Casual      1        True
3  2011-01-17     1      Member     15        True
4  2011-01-17     2      Member      8        True

In [66]:
rides_by_hour_with_holidays = pd.merge(
    rides_by_hour,
    holidays,
    left_on='date',
    right_on='date',
    how='left',
    indicator=True)
rides_by_hour_with_holidays.head()

         date  hour Member type  rides is_holiday     _merge
0  2011-01-01     0      Casual      3        NaN  left_only
1  2011-01-01     0      Member     13        NaN  left_only
2  2011-01-01     1      Casual      8        NaN  left_only
3  2011-01-01     1      Member     30        NaN  left_only
4  2011-01-01     2      Casual      5        NaN  left_only

In [67]:
rides_by_hour_with_holidays['is_holiday'] = rides_by_hour_with_holidays['is_holiday'].fillna(False)

In [69]:
rides_by_hour_with_holidays.head()

         date  hour Member type  rides  is_holiday     _merge
0  2011-01-01     0      Casual      3       False  left_only
1  2011-01-01     0      Member     13       False  left_only
2  2011-01-01     1      Casual      8       False  left_only
3  2011-01-01     1      Member     30       False  left_only
4  2011-01-01     2      Casual      5       False  left_only

https://www.ncei.noaa.gov/data/global-hourly/doc/isd-format-document.pdf
https://www.ncei.noaa.gov/data/global-hourly/doc/CSV_HELP.pdf

There's a "Find a Station" tool, but it's confusing how to use the results. https://www.ncdc.noaa.gov/data-access/land-based-station-data/station-metadata has a link to a [station list file](ftp://ftp.ncdc.noaa.gov/pub/data/noaa/isd-history.txt). Searching that, it looks like the code for Reagan Airport is 724050 13743. So the file is
https://www.ncei.noaa.gov/data/global-hourly/access/2011/72405013743.csv

In [70]:
weather = pd.read_csv("https://www.ncei.noaa.gov/data/global-hourly/access/2011/72405013743.csv")

//anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3057: DtypeWarning: Columns (43,47,51,55) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [75]:
weather['date'] = pd.to_datetime(weather['DATE'])

In [80]:
weather['date_hr'] = weather.date.dt.round(freq="H")

In [87]:
weather['TMP'].str.split(',', n=1, expand=True)

           0  1
0      +0056  1
1      +0056  5
2      +0050  5
3      +0039  5
4      +0039  1
5      +0022  5
6      +0033  5
7      +9999  9
8      +9999  9
9      +0017  5
10     +0017  1
11     +0022  5
12     +0028  5
13     +0022  5
14     +0022  1
15     +0028  5
16     +0022  5
17     +0011  5
18     +0011  1
19     +0028  5
20     +0067  5
21     +0100  5
22     +0100  1
23     +0094  5
24     +0120  5
25     +0117  5
26     +0133  5
27     +0133  1
28     +0140  5
29     +0140  5
...      ... ..
14528  +0094  5
14529  +0100  5
14530  +9999  9
14531  +0106  5
14532  +0106  1
14533  +0106  5
14534  +0106  5
14535  +0100  5
14536  +0100  1
14537  +0094  5
14538  +0106  5
14539  +0100  5
14540  +0100  1
14541  +0083  5
14542  +0100  5
14543  +0111  5
14544  +0111  1
14545  +0122  5
14546  +0167  5
14547  +0156  5
14548  +0156  1
14549  +0144  5
14550  +0144  5
14551  +0133  5
14552  +0133  1
14553  +0130  5
14554  +0122  5
14555  +0120  5
14556  +0117  5
14557  +0111  5

[14558 rows x 2 columns]

In [90]:
weather[['temp', 'temp_validity']] = weather['TMP'].str.split(',', n=1, expand=True)

In [92]:
weather['temp'] = pd.to_numeric(weather['temp'])

In [95]:
weather[['temp','temp_validity']]

       temp temp_validity
0        56             1
1        56             5
2        50             5
3        39             5
4        39             1
5        22             5
6        33             5
7      9999             9
8      9999             9
9        17             5
10       17             1
11       22             5
12       28             5
13       22             5
14       22             1
15       28             5
16       22             5
17       11             5
18       11             1
19       28             5
20       67             5
21      100             5
22      100             1
23       94             5
24      120             5
25      117             5
26      133             5
27      133             1
28      140             5
29      140             5
...     ...           ...
14528    94             5
14529   100             5
14530  9999             9
14531   106             5
14532   106             1
14533   106             5
14534   106             5
14535   100             5
14536   100             1
14537    94             5
14538   106             5
14539   100             5
14540   100             1
14541    83             5
14542   100             5
14543   111             5
14544   111             1
14545   122             5
14546   167             5
14547   156             5
14548   156             1
14549   144             5
14550   144             5
14551   133             5
14552   133             1
14553   130             5
14554   122             5
14555   120             5
14556   117             5
14557   111             5

[14558 rows x 2 columns]

In [96]:
weather['temp_validity'].value_counts()

5    11266
1     2906
9      378
A        7
6        1
Name: temp_validity, dtype: int64