# DataTables, Indexes, Pandas, and Seaborn

## Some useful (free) resources

Introductory:

* [Getting started with Python for research](https://github.com/TiesdeKok/LearnPythonforResearch), a gentle introduction to Python in data-intensive research.

* [A Whirlwind Tour of Python](https://jakevdp.github.io/WhirlwindTourOfPython/index.html), by Jake VanderPlas, another quick Python intro (with notebooks).

Core Pandas/Data Science books:

* [The Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/), by Jake VanderPlas.

* [Python for Data Analysis, 2nd Edition](http://proquest.safaribooksonline.com/book/programming/python/9781491957653), by  Wes McKinney, creator of Pandas. [Companion Notebooks](https://github.com/wesm/pydata-book)

* [Effective Pandas](https://github.com/TomAugspurger/effective-pandas), a book by Tom Augspurger, core Pandas developer.


Complementary resources:

* [An introduction to "Data Science"](https://github.com/stefanv/ds_intro), a collection of Notebooks by BIDS' [Stéfan Van der Walt](https://bids.berkeley.edu/people/st%C3%A9fan-van-der-walt).

* [Effective Computation in Physics](http://proquest.safaribooksonline.com/book/physics/9781491901564), by Kathryn D. Huff; Anthony Scopatz. [Notebooks to accompany the book](https://github.com/physics-codes/seminar). Don't be fooled by the title, it's a great book on modern computational practices with very little that's physics-specific.


OK, let's load and configure some of our core libraries (as an aside, you can find a nice visual gallery of available matplotlib styles [here](https://tonysyu.github.io/raw_content/matplotlib-style-gallery/gallery.html)).

In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

sns.set()
sns.set_context('talk')
np.set_printoptions(threshold=20, precision=2, suppress=True)
pd.options.display.max_rows = 10
pd.options.display.max_columns = 8
pd.set_option('precision', 2)
# This option stops scientific notation for pandas
# pd.set_option('display.float_format', '{:.2f}'.format)

## Reading in DataFrames from Files

Pandas has a number of very useful file reading tools. You can see them enumerated by typing "pd.re" and pressing tab. We'll be using read_csv today.

In [2]:
elections = pd.read_csv("elections.csv")
elections # if we end a cell with an expression or variable name, the result will print

   Candidate        Party     %  Year Result
0     Reagan   Republican  50.7  1980    win
1     Carter   Democratic  41.0  1980   loss
2   Anderson  Independent   6.6  1980   loss
3     Reagan   Republican  58.8  1984    win
4    Mondale   Democratic  37.6  1984   loss
..       ...          ...   ...   ...    ...
18    McCain   Republican  45.7  2008   loss
19     Obama   Democratic  51.1  2012    win
20    Romney   Republican  47.2  2012   loss
21   Clinton   Democratic  48.2  2016   loss
22     Trump   Republican  46.1  2016    win

[23 rows x 5 columns]

In [3]:
elections.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 5 columns):
Candidate    23 non-null object
Party        23 non-null object
%            23 non-null float64
Year         23 non-null int64
Result       23 non-null object
dtypes: float64(1), int64(1), object(3)
memory usage: 1000.0+ bytes

In [4]:
elections.shape

(23, 5)

In [4]:
elections.size

115

In [5]:
elections.describe()

           %     Year
count  23.00    23.00
mean   42.51  1996.87
std    13.48    11.63
...      ...      ...
50%    47.20  1996.00
75%    49.95  2006.00
max    58.80  2016.00

[8 rows x 2 columns]

We can use the head command to show only a few rows of a dataframe.

In [6]:
elections.head(7)

  Candidate        Party     %  Year Result
0    Reagan   Republican  50.7  1980    win
1    Carter   Democratic  41.0  1980   loss
2  Anderson  Independent   6.6  1980   loss
3    Reagan   Republican  58.8  1984    win
4   Mondale   Democratic  37.6  1984   loss
5      Bush   Republican  53.4  1988    win
6   Dukakis   Democratic  45.6  1988   loss

There is also a tail command.

In [7]:
elections.tail(7)

   Candidate       Party     %  Year Result
16      Bush  Republican  50.7  2004    win
17     Obama  Democratic  52.9  2008    win
18    McCain  Republican  45.7  2008   loss
19     Obama  Democratic  51.1  2012    win
20    Romney  Republican  47.2  2012   loss
21   Clinton  Democratic  48.2  2016   loss
22     Trump  Republican  46.1  2016    win

The read_csv command lets us specify a column to use an index. For example, we could have used Year as the index.

In [8]:
elections_year_index = pd.read_csv("elections.csv", index_col = "Year")
elections_year_index.head(5)

     Candidate        Party     % Result
Year
1980    Reagan   Republican  50.7    win
1980    Carter   Democratic  41.0   loss
1980  Anderson  Independent   6.6   loss
1984    Reagan   Republican  58.8    win
1984   Mondale   Democratic  37.6   loss

Alternately, we could have used the set_index commmand.

In [9]:
elections_party_index = elections.set_index("Party")
elections_party_index.head(5)

            Candidate     %  Year Result
Party
Republican     Reagan  50.7  1980    win
Democratic     Carter  41.0  1980   loss
Independent  Anderson   6.6  1980   loss
Republican     Reagan  58.8  1984    win
Democratic    Mondale  37.6  1984   loss

The set_index command (along with almost all other data frame methods) does not modify the dataframe. That is, the original "elections" is untouched. Note: There is a flag called "inplace" which does modify the calling dataframe.

In [10]:
elections.head() #the index remains unchanged

  Candidate        Party     %  Year Result
0    Reagan   Republican  50.7  1980    win
1    Carter   Democratic  41.0  1980   loss
2  Anderson  Independent   6.6  1980   loss
3    Reagan   Republican  58.8  1984    win
4   Mondale   Democratic  37.6  1984   loss

In [11]:
original = elections
elections = elections.set_index('Year')

original.head(2)

  Candidate       Party     %  Year Result
0    Reagan  Republican  50.7  1980    win
1    Carter  Democratic  41.0  1980   loss

In [12]:
elections.head(2)

     Candidate       Party     % Result
Year
1980    Reagan  Republican  50.7    win
1980    Carter  Democratic  41.0   loss

In [13]:
elections = original
elections.set_index('Year', inplace=True)
original.head(2)

     Candidate       Party     % Result
Year
1980    Reagan  Republican  50.7    win
1980    Carter  Democratic  41.0   loss

In [14]:
elections = pd.read_csv('elections.csv')
elections.head(2)

  Candidate       Party     %  Year Result
0    Reagan  Republican  50.7  1980    win
1    Carter  Democratic  41.0  1980   loss

By contast, column names MUST be unique. For example, if we try to read in a file for which column names are not unique, Pandas will automatically any duplicates.

## The [] Operator

The DataFrame class has an indexing operator [] that lets you do a variety of different things. If your provide a String to the [] operator, you get back a Series corresponding to the requested label.

In [5]:
elections["Candidate"].head(6)

0      Reagan
1      Carter
2    Anderson
3      Reagan
4     Mondale
5        Bush
Name: Candidate, dtype: object

The [] operator also accepts a list of strings. In this case, you get back a DataFrame corresponding to the requested strings.

In [6]:
elections[["Candidate", "Party"]].head(6)

  Candidate        Party
0    Reagan   Republican
1    Carter   Democratic
2  Anderson  Independent
3    Reagan   Republican
4   Mondale   Democratic
5      Bush   Republican

A list of one label also returns a DataFrame. This can be handy if you want your results as a DataFrame, not a series.

In [7]:
elections[["Candidate"]].head(6)

  Candidate
0    Reagan
1    Carter
2  Anderson
3    Reagan
4   Mondale
5      Bush

Note that we can also use the to_frame method to turn a Series into a DataFrame.

In [18]:
elections["Candidate"].to_frame()

   Candidate
0     Reagan
1     Carter
2   Anderson
..       ...
20    Romney
21   Clinton
22     Trump

[23 rows x 1 columns]

The [] operator also accepts numerical slices as arguments. In this case, we are indexing by row, not column!

In [80]:
elections[0:3]

  Candidate        Party     %  Year Result
0    Reagan   Republican  50.7  1980    win
1    Carter   Democratic  41.0  1980   loss
2  Anderson  Independent   6.6  1980   loss

If you provide a single argument to the [] operator, it tries to use it as a name. This is true even if the argument passed to [] is an integer.

In [81]:
#elections[0] #this does not work, try uncommenting this to see it fail in action, woo

The following cells allow you to test your understanding.

In [82]:
weird = pd.DataFrame({1:["topdog","botdog"], "1":["topcat","botcat"]})
weird

        1       1
0  topdog  topcat
1  botdog  botcat

In [83]:
weird[1] #try to predict the output

0    topdog
1    botdog
Name: 1, dtype: object

In [84]:
weird[["1"]] #try to predict the output

        1
0  topcat
1  botcat

In [85]:
weird[1:] #try to predict the output

        1       1
1  botdog  botcat

## Boolean Array Selection

The `[]` operator also supports array of booleans as an input. In this case, the array must be exactly as long as the number of rows. The result is a filtered version of the data frame, where only rows corresponding to True appear.

In [19]:
elections[[False, False, False, False, False, 
          False, False, True, False, False,
          True, False, False, False, True,
          False, False, False, False, False,
          False, False, True]]

   Candidate       Party     %  Year Result
7    Clinton  Democratic  43.0  1992    win
10   Clinton  Democratic  49.2  1996    win
14      Bush  Republican  47.9  2000    win
22     Trump  Republican  46.1  2016    win

One very common task in Data Science is filtering. Boolean Array Selection is one way to achieve this in Pandas. We start by observing logical operators like the equality operator can be applied to Pandas Series data to generate a Boolean Array. For example, we can compare the 'Result' column to the String 'win':

In [20]:
elections.head(5)

  Candidate        Party     %  Year Result
0    Reagan   Republican  50.7  1980    win
1    Carter   Democratic  41.0  1980   loss
2  Anderson  Independent   6.6  1980   loss
3    Reagan   Republican  58.8  1984    win
4   Mondale   Democratic  37.6  1984   loss

In [8]:
iswin = elections['Result'] == 'win'
iswin.head(5)

0     True
1    False
2    False
3     True
4    False
Name: Result, dtype: bool

In [9]:
elections[iswin]

   Candidate       Party     %  Year Result
0     Reagan  Republican  50.7  1980    win
3     Reagan  Republican  58.8  1984    win
5       Bush  Republican  53.4  1988    win
7    Clinton  Democratic  43.0  1992    win
10   Clinton  Democratic  49.2  1996    win
14      Bush  Republican  47.9  2000    win
16      Bush  Republican  50.7  2004    win
17     Obama  Democratic  52.9  2008    win
19     Obama  Democratic  51.1  2012    win
22     Trump  Republican  46.1  2016    win

The output of the logical operator applied to the Series is another Series with the same name and index, but of datatype boolean. The entry with index i represents the result of the application of that operator to the entry of the original Series with index i.

In [23]:
elections[elections['Party'] == 'Independent']

   Candidate        Party     %  Year Result
2   Anderson  Independent   6.6  1980   loss
9      Perot  Independent  18.9  1992   loss
12     Perot  Independent   8.4  1996   loss

In [24]:
elections['Result'].head(5)

0     win
1    loss
2    loss
3     win
4    loss
Name: Result, dtype: object

These boolean Series can be used as an argument to the [] operator. For example, the following code creates a DataFrame of all election winners since 1980.

In [25]:
elections.loc[iswin]

   Candidate       Party     %  Year Result
0     Reagan  Republican  50.7  1980    win
3     Reagan  Republican  58.8  1984    win
5       Bush  Republican  53.4  1988    win
..       ...         ...   ...   ...    ...
17     Obama  Democratic  52.9  2008    win
19     Obama  Democratic  51.1  2012    win
22     Trump  Republican  46.1  2016    win

[10 rows x 5 columns]

Above, we've assigned the result of the logical operator to a new variable called `iswin`. This is uncommon. Usually, the series is created and used on the same line. Such code is a little tricky to read at first, but you'll get used to it quickly.

In [26]:
elections[elections['Result'] == 'win']

   Candidate       Party     %  Year Result
0     Reagan  Republican  50.7  1980    win
3     Reagan  Republican  58.8  1984    win
5       Bush  Republican  53.4  1988    win
..       ...         ...   ...   ...    ...
17     Obama  Democratic  52.9  2008    win
19     Obama  Democratic  51.1  2012    win
22     Trump  Republican  46.1  2016    win

[10 rows x 5 columns]

We can select multiple criteria by creating multiple boolean Series and combining them using the `&` operator.

In [16]:
elections[(elections['Result'] == 'win')
          & (elections['%'] < 50)]

   Candidate       Party     %  Year Result
7    Clinton  Democratic  43.0  1992    win
10   Clinton  Democratic  49.2  1996    win
14      Bush  Republican  47.9  2000    win
22     Trump  Republican  46.1  2016    win

## Loc and ILOC

In [28]:
elections.head(5)

  Candidate        Party     %  Year Result
0    Reagan   Republican  50.7  1980    win
1    Carter   Democratic  41.0  1980   loss
2  Anderson  Independent   6.6  1980   loss
3    Reagan   Republican  58.8  1984    win
4   Mondale   Democratic  37.6  1984   loss

In [38]:
list(elections["Year"].mode())

[1980, 1992, 1996]

In [21]:
elections[["Party","Year"]]

          Party  Year
0    Republican  1980
1    Democratic  1980
2   Independent  1980
3    Republican  1984
4    Democratic  1984
..          ...   ...
18   Republican  2008
19   Democratic  2012
20   Republican  2012
21   Democratic  2016
22   Republican  2016

[23 rows x 2 columns]

In [25]:
weird = elections.loc[[4, 2, 1, 3], ['Candidate','Party', 'Year']]
weird

  Candidate        Party  Year
4   Mondale   Democratic  1984
2  Anderson  Independent  1980
1    Carter   Democratic  1980
3    Reagan   Republican  1984

In [30]:
weird.iloc[2]

Candidate        Carter
Party        Democratic
Year               1980
Name: 1, dtype: object

In [24]:
elections.sort_values('Party')

   Candidate       Party     %  Year Result
1     Carter  Democratic  41.0  1980   loss
4    Mondale  Democratic  37.6  1984   loss
19     Obama  Democratic  51.1  2012    win
6    Dukakis  Democratic  45.6  1988   loss
7    Clinton  Democratic  43.0  1992    win
..       ...         ...   ...   ...    ...
8       Bush  Republican  37.4  1992   loss
5       Bush  Republican  53.4  1988    win
3     Reagan  Republican  58.8  1984    win
16      Bush  Republican  50.7  2004    win
22     Trump  Republican  46.1  2016    win

[23 rows x 5 columns]

Loc also supports slicing (for all types, including numeric and string labels!). Note that the slicing for loc is **inclusive**, even for numeric slices.

In [32]:
elections.loc[0:4, 'Candidate':'Year']

  Candidate        Party     %  Year
0    Reagan   Republican  50.7  1980
1    Carter   Democratic  41.0  1980
2  Anderson  Independent   6.6  1980
3    Reagan   Republican  58.8  1984
4   Mondale   Democratic  37.6  1984

If we provide only a single label for the column argument, we get back a Series.

In [33]:
elections.loc[0:4, 'Candidate']

0      Reagan
1      Carter
2    Anderson
3      Reagan
4     Mondale
Name: Candidate, dtype: object

If we want a data frame instead and don't want to use to_frame, we can provde a list containing the column name.

In [34]:
elections.loc[0:4, ['Candidate']]

  Candidate
0    Reagan
1    Carter
2  Anderson
3    Reagan
4   Mondale

If we give only one row but many column labels, we'll get back a Series corresponding to a row of the table. This new Series has a neat index, where each entry is the name of the column that the data came from.

In [35]:
elections.loc[0, 'Candidate':'Year']

Candidate        Reagan
Party        Republican
%                    51
Year               1980
Name: 0, dtype: object

In [36]:
elections.loc[[0], 'Candidate':'Year']

  Candidate       Party     %  Year
0    Reagan  Republican  50.7  1980

If we omit the column argument altogether, the default behavior is to retrieve all columns.

In [37]:
elections.loc[[2, 4, 5]]

  Candidate        Party     %  Year Result
2  Anderson  Independent   6.6  1980   loss
4   Mondale   Democratic  37.6  1984   loss
5      Bush   Republican  53.4  1988    win

Loc also supports boolean array inputs instead of labels. If the arrays are too short, loc assumes the missing values are False.

In [38]:
elections.loc[[True, False, False, True], [True, False, False, True]]

  Candidate  Year
0    Reagan  1980
3    Reagan  1984

In [39]:
elections.loc[[0, 3], ['Candidate', 'Year']]

  Candidate  Year
0    Reagan  1980
3    Reagan  1984

We can use boolean array arguments for one axis of the data, and labels for the other.

In [40]:
elections.loc[[True, False, False, True], 'Candidate':'%']

  Candidate       Party     %
0    Reagan  Republican  50.7
3    Reagan  Republican  58.8

Boolean Series are also boolean arrays, so we can use the Boolean Array Selection from earlier using loc as well.

In [41]:
elections.loc[(elections['Result'] == 'win') & (elections['%'] < 50), 
              'Candidate':'%']

   Candidate       Party     %
7    Clinton  Democratic  43.0
10   Clinton  Democratic  49.2
14      Bush  Republican  47.9
22     Trump  Republican  46.1

Let's do a quick example using data with string-labeled rows instead of integer labeled rows, just to make sure we're really understanding loc.

In [42]:
mottos = pd.read_csv("mottos.csv", index_col = "State")
mottos.head(5)

,Motto,Translation,Language,Date Adopted
State,,,,
Alabama,Audemus jura nostra defendere,We dare defend our rights!,Latin,1923
Alaska,North to the future,—,English,1967
Arizona,Ditat Deus,God enriches,Latin,1863
Arkansas,Regnat populus,The people rule,Latin,1907
California,Eureka (Εὕρηκα),I have found it,Greek,1849

As you'd expect, the rows to extract can be specified using slice notation, even if the rows have string labels instead of integer labels.

In [43]:
mottos.loc['California':'Florida', ['Motto', 'Language']]

                                Motto Language
State
California            Eureka (Εὕρηκα)    Greek
Colorado              Nil sine numine    Latin
Connecticut   Qui transtulit sustinet    Latin
Delaware     Liberty and Independence  English
Florida               In God We Trust  English

Let's load up another bigger dataframe for practice.

In [45]:
mottos_extreme = pd.read_csv("mottos_extreme.csv", index_col='State')
mottos_extreme.loc['California']

                                 Motto      Translation Language Date Adopted
State
California             Eureka (Εὕρηκα)  I have found it    Greek         1849
California  We are the real California                —  English         2006

### iloc

loc's cousin iloc is very similar, but is used to access based on numerical position instead of label. For example, to access to the top 3 rows and top 3 columns of a table, we can use [0:3, 0:3]. iloc slicing is **exclusive**, just like standard Python slicing of numerical values.

In [46]:
elections.head(5)

  Candidate        Party     %  Year Result
0    Reagan   Republican  50.7  1980    win
1    Carter   Democratic  41.0  1980   loss
2  Anderson  Independent   6.6  1980   loss
3    Reagan   Republican  58.8  1984    win
4   Mondale   Democratic  37.6  1984   loss

In [47]:
elections.iloc[0:3, 0:3]

  Candidate        Party     %
0    Reagan   Republican  50.7
1    Carter   Democratic  41.0
2  Anderson  Independent   6.6

In [48]:
mottos.iloc[0:3, 0:3]

                                 Motto                 Translation Language
State
Alabama  Audemus jura nostra defendere  We dare defend our rights!    Latin
Alaska             North to the future                           —  English
Arizona                     Ditat Deus                God enriches    Latin

We will use both loc and iloc in the course. Loc is generally preferred for a number of reasons, for example: 

1. It is harder to make mistakes since you have to literally write out what you want to get.
2. Code is easier to read, because the reader doesn't have to know e.g. what column #31 represents.
3. It is robust against permutations of the data, e.g. the social security administration switches the order of two columns.

However, iloc is sometimes more convenient. We'll provide examples of when iloc is the superior choice.

## Handy Properties and Utility Functions for Series and DataFrames

The head, shape, size, and describe methods can be used to quickly get a good sense of the data we're working with. For example:

In [49]:
mottos.head(5)

,Motto,Translation,Language,Date Adopted
State,,,,
Alabama,Audemus jura nostra defendere,We dare defend our rights!,Latin,1923
Alaska,North to the future,—,English,1967
Arizona,Ditat Deus,God enriches,Latin,1863
Arkansas,Regnat populus,The people rule,Latin,1907
California,Eureka (Εὕρηκα),I have found it,Greek,1849

In [50]:
mottos.size

200

The fact that the size is 200 means our data file is relatively small, with only 200 total entries.

In [51]:
mottos.shape

(50, 4)

Since we're looking at data for states, and we see the number 50, it looks like we've mostly likely got a complete dataset that omits Washington D.C. and U.S. territories like Guam and Puerto Rico.

In [52]:
mottos.describe()

             Motto Translation Language Date Adopted
count           50          49       50           50
unique          50          30        8           47
top     Friendship           —    Latin         1847
freq             1          20       23            2

Above, we see a quick summary of all the data. For example, the most common language for mottos is Latin, which covers 23 different states. Does anything else seem surprising?

We can get a direct reference to the index using .index.

In [53]:
mottos.index

Index(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado',
       'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho',
       'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana',
       'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota',
       'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada',
       'New Hampshire', 'New Jersey', 'New Mexico', 'New York',
       'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon',
       'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota',
       'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
       'West Virginia', 'Wisconsin', 'Wyoming'],
      dtype='object', name='State')

We can also access individual properties of the index, for example, `mottos.index.name`.

In [54]:
mottos.index.name

'State'

This reflects the fact that in our data frame, the index IS the state!

In [55]:
mottos.head(2)

,Motto,Translation,Language,Date Adopted
State,,,,
Alabama,Audemus jura nostra defendere,We dare defend our rights!,Latin,1923
Alaska,North to the future,—,English,1967

It turns out the columns also have an Index. We can access this index by using `.columns`.

In [56]:
mottos.columns

Index(['Motto', 'Translation', 'Language', 'Date Adopted'], dtype='object')

There are also a ton of useful utility methods we can use with Data Frames and Series. For example, we can create a copy of a data frame sorted by a specific column using `sort_values`.

In [57]:
elections.sort_values('%')

   Candidate        Party     %  Year Result
2   Anderson  Independent   6.6  1980   loss
12     Perot  Independent   8.4  1996   loss
9      Perot  Independent  18.9  1992   loss
..       ...          ...   ...   ...    ...
17     Obama   Democratic  52.9  2008    win
5       Bush   Republican  53.4  1988    win
3     Reagan   Republican  58.8  1984    win

[23 rows x 5 columns]

As mentioned before, all Data Frame methods return a copy and do **not** modify the original data structure, unless you set inplace to True.

In [58]:
elections.head(5)

  Candidate        Party     %  Year Result
0    Reagan   Republican  50.7  1980    win
1    Carter   Democratic  41.0  1980   loss
2  Anderson  Independent   6.6  1980   loss
3    Reagan   Republican  58.8  1984    win
4   Mondale   Democratic  37.6  1984   loss

If we want to sort in reverse order, we can set `ascending=False`.

In [59]:
elections.sort_values('%', ascending=False)

   Candidate        Party     %  Year Result
3     Reagan   Republican  58.8  1984    win
5       Bush   Republican  53.4  1988    win
17     Obama   Democratic  52.9  2008    win
..       ...          ...   ...   ...    ...
9      Perot  Independent  18.9  1992   loss
12     Perot  Independent   8.4  1996   loss
2   Anderson  Independent   6.6  1980   loss

[23 rows x 5 columns]

We can also use `sort_values` on Series objects.

In [60]:
mottos['Language'].sort_values().head(10)

State
Washington      Chinook Jargon
Wyoming                English
New Jersey             English
                     ...
Pennsylvania           English
Rhode Island           English
South Dakota           English
Name: Language, Length: 10, dtype: object

For Series, the `value_counts` method is often quite handy.

In [61]:
elections['Party'].value_counts()

Republican     10
Democratic     10
Independent     3
Name: Party, dtype: int64

In [62]:
mottos['Language'].value_counts()

Latin       23
English     21
Greek        1
            ..
Spanish      1
Hawaiian     1
French       1
Name: Language, Length: 8, dtype: int64

Also commonly used is the `unique` method, which returns all unique values as a numpy array.

In [63]:
mottos['Language'].unique()

array(['Latin', 'English', 'Greek', 'Hawaiian', 'Italian', 'French',
       'Spanish', 'Chinook Jargon'], dtype=object)

## Case Study: What was the most popular name in Michigan last year (2019)?

https://www.ssa.gov/OACT/babynames/index.html

https://www.ssa.gov/data

We can download data from the internet with Python, and do so only if needed:

In [65]:
import requests
from pathlib import Path

namesbystate_path = Path('namesbystate.zip')
data_url = 'https://www.ssa.gov/oact/babynames/state/namesbystate.zip'

if not namesbystate_path.exists():
    print('Downloading...', end=' ')
    resp = requests.get(data_url)
    with namesbystate_path.open('wb') as f:
        f.write(resp.content)
    print('Done!')
else:
    print("File already downloaded.")

File already downloaded.

Let's use Python to understand how this data is laid out:

In [66]:
import zipfile
zf = zipfile.ZipFile(namesbystate_path, 'r')
print([f.filename for f in zf.filelist])

['AK.TXT', 'AL.TXT', 'AR.TXT', 'AZ.TXT', 'CA.TXT', 'CO.TXT', 'CT.TXT', 'DC.TXT', 'DE.TXT', 'FL.TXT', 'GA.TXT', 'HI.TXT', 'IA.TXT', 'ID.TXT', 'IL.TXT', 'IN.TXT', 'KS.TXT', 'KY.TXT', 'LA.TXT', 'MA.TXT', 'MD.TXT', 'ME.TXT', 'MI.TXT', 'MN.TXT', 'MO.TXT', 'MS.TXT', 'MT.TXT', 'NC.TXT', 'ND.TXT', 'NE.TXT', 'NH.TXT', 'NJ.TXT', 'NM.TXT', 'NV.TXT', 'NY.TXT', 'OH.TXT', 'OK.TXT', 'OR.TXT', 'PA.TXT', 'RI.TXT', 'SC.TXT', 'SD.TXT', 'StateReadMe.pdf', 'TN.TXT', 'TX.TXT', 'UT.TXT', 'VA.TXT', 'VT.TXT', 'WA.TXT', 'WI.TXT', 'WV.TXT', 'WY.TXT']

We can pull the PDF readme to view it, but let's operate with the rest of the data in its compressed state:

In [67]:
zf.extract('StateReadMe.pdf')

'/Users/kcarnold/code/Teaching/data202/src/week2/StateReadMe.pdf'

Let's have a look at the Michigan data, it should give us an idea about the structure of the whole thing:

In [71]:
mi_name = 'MI.TXT'
with zf.open(mi_name) as f:
    for i in range(10):
        print(f.readline().rstrip())

b'MI,F,1910,Helen,368'
b'MI,F,1910,Mary,349'
b'MI,F,1910,Margaret,272'
b'MI,F,1910,Dorothy,265'
b'MI,F,1910,Ruth,212'
b'MI,F,1910,Florence,164'
b'MI,F,1910,Mildred,159'
b'MI,F,1910,Frances,155'
b'MI,F,1910,Anna,143'
b'MI,F,1910,Marie,143'

This is equivalent (on macOS or Linux) to extracting the full `MI.TXT` file to disk and then using the `head` command (if you're on Windows, don't try to run the cell below):

In [72]:
zf.extract(mi_name)
!head {mi_name}

In [73]:
!echo {mi_name}

MI.TXT

A couple of practical comments:

* The above is using special tricks in Jupyter's "IPython" kernels that let you call operating system commands via `!cmd`, and that expand Python variables in such commands with the `{var}` syntax. You can find more about IPython's special tricks [in this tutorial](https://github.com/ipython/ipython-in-depth/blob/master/examples/IPython%20Kernel/Beyond%20Plain%20Python.ipynb).

* `head` doesn't work on Windows, though there are equivalent Windows commands. But by using Python code, even if it's a little bit more verbose, we have a 100% portable solution.

* If the `MI.TXT` file was huge, it would be wasteful to write it all to disk only to look at the start of the file.

The last point is an important, and general theme of this course: we need to learn how to operate with data only on an as-needed basis, because there are many situations in the real world where we can't afford to brute-force 'download all the things'.

Let's remove the `MI.TXT` file to make sure we keep working with our compressed data, as if we couldn't extract it:

In [74]:
import os; os.unlink(mi_name)

## Question 1: What was the most popular name in MI last year?

In [97]:
def load_names_for_state(state):
    field_names = ['State', 'Sex', 'Year', 'Name', 'Count']
    with zf.open(f'{state}.TXT') as fh:
        return pd.read_csv(fh, header=None, names=field_names)
mi = load_names_for_state('MI')
mi.head()

  State Sex  Year      Name  Count
0    MI   F  1910     Helen    368
1    MI   F  1910      Mary    349
2    MI   F  1910  Margaret    272
3    MI   F  1910   Dorothy    265
4    MI   F  1910      Ruth    212

### Indexing Review

Let's play around a bit with our indexing techniques from earlier today.

In [78]:
mi['Count'].head()

0    368
1    349
2    272
3    265
4    212
Name: Count, dtype: int64

In [79]:
mi[0:3]

  State Sex  Year      Name  Count
0    MI   F  1910     Helen    368
1    MI   F  1910      Mary    349
2    MI   F  1910  Margaret    272

In [80]:
mi.iloc[:3, -2:]

       Name  Count
0     Helen    368
1      Mary    349
2  Margaret    272

In [81]:
mi.loc[0:3, 'State']

0    MI
1    MI
2    MI
3    MI
Name: State, dtype: object

In [82]:
mi['Name'].head()

0       Helen
1        Mary
2    Margaret
3     Dorothy
4        Ruth
Name: Name, dtype: object

In [83]:
mi[['Name']].head()

       Name
0     Helen
1      Mary
2  Margaret
3   Dorothy
4      Ruth

In [84]:
mi[mi['Year'] == 2017].tail()

       State Sex  Year       Name  Count
179161    MI   M  2017   Wolfgang      5
179162    MI   M  2017     Xavion      5
179163    MI   M  2017      Zayan      5
179164    MI   M  2017  Zephaniah      5
179165    MI   M  2017      Zyler      5

## Understanding the Data

In [85]:
mi.head()

  State Sex  Year      Name  Count
0    MI   F  1910     Helen    368
1    MI   F  1910      Mary    349
2    MI   F  1910  Margaret    272
3    MI   F  1910   Dorothy    265
4    MI   F  1910      Ruth    212

In [90]:
mi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 179166 entries, 0 to 179165
Data columns (total 5 columns):
State    179166 non-null object
Sex      179166 non-null object
Year     179166 non-null int64
Name     179166 non-null object
Count    179166 non-null int64
dtypes: int64(2), object(3)
memory usage: 6.8+ MB

We can get a sense for the shape of our data:

In [86]:
mi.shape

(179166, 5)

Pandas will give us a summary overview of the *numerical* data in the DataFrame:

In [88]:
mi.describe()

            Year      Count
count  179166.00  179166.00
mean     1975.00      67.00
std        29.48     214.52
...          ...        ...
50%      1979.00      13.00
75%      2001.00      38.00
max      2017.00    4925.00

[8 rows x 2 columns]

### Sorting

What we've done so far is NOT exploratory data analysis. We were just playing around a bit with the capabilities of the pandas library. Now that we're done, let's turn to the problem at hand: Identifying the most common name in Michigan last year.

In [94]:
mi2017 = mi[mi['Year'] == 2017]
mi_sorted = mi2017.sort_values('Count', ascending=False)
mi_sorted.head(10)

       State Sex  Year      Name  Count
100473    MI   F  2017      Emma    531
100474    MI   F  2017       Ava    526
177912    MI   M  2017      Liam    505
100475    MI   F  2017    Olivia    505
177913    MI   M  2017      Noah    476
177914    MI   M  2017    Oliver    459
177915    MI   M  2017     Lucas    436
177916    MI   M  2017     Mason    432
177917    MI   M  2017  Benjamin    429
177918    MI   M  2017     Logan    426

How does that compare with Massachusetts?

In [98]:
ma_names = load_names_for_state('MA')

In [101]:
ma2017 = ma_names[ma_names['Year'] == 2017]
ma2017.sort_values("Count", ascending=False).head(10)

       State Sex  Year       Name  Count
115435    MA   M  2017   Benjamin    492
115436    MA   M  2017    William    421
65939     MA   F  2017       Emma    393
65940     MA   F  2017     Olivia    379
115438    MA   M  2017      Lucas    373
115437    MA   M  2017       Liam    373
115439    MA   M  2017       Noah    365
65941     MA   F  2017  Charlotte    347
115440    MA   M  2017      James    337
65942     MA   F  2017     Sophia    330

Bonus: what is the meaning of this?

In [103]:
(mi2017.Sex == "M").mean()

0.4578313253012048

In [102]:
(ma2017.Sex == "M").mean()

0.4486396446418656